lint.select = ["ALL"]

# Ignore incompatible rules
lint.ignore = [
    "D203", # one-blank-line-before-class
    "D213", # multi-line-summary-second-line
]

[lint.per-file-ignores]
# Allow assert in tests
"test_*.py" = ["S101"]
# Allow print in scripts that writes to STDOUT
"mergeduplicates.py" = ["T201"]
"removesuperfluouscols.py" = ["T201"]
