name: Python

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black mypy pylama pytest ruff
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: black
        run: |
          black --diff --check .
      - name: mypy
        run: |
          mypy $(git ls-files '*.py')
      - name: pytest
        run: |
          pytest
      - name: pylama
        run: |
          pylama
      - name: ruff
        run: |
          ruff --format=github --select=E9,F63,F7,F82 --target-version=py39 .
          ruff --format=github --target-version=py39 .
