name: Python

on: [workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            apt-get update
            apt-get install -y imagemagick poppler-utils
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew update
            brew install poppler imagemagick
          else
            echo "$RUNNER_OS not supported"
            exit 1
          fi
          python -m pip install --upgrade pip
          pip install setuptools black mypy pylama pylint pytest pytest-cov pytest-pylint ruff
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi
      - name: black
        run: |
          black --diff --check .
      - name: mypy
        run: |
          mypy $(git ls-files '*.py')
      - name: pylama
        run: |
          pylama
      - name: pylint
        run: |
          pylint $(git ls-files '*.py')
      - name: pytest
        run: |
          pytest
      - name: ruff
        run: |
          ruff check --output-format=github --select=E9,F63,F7,F82 --target-version=py39 .
          ruff check --output-format=github --target-version=py39 .
